language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.1
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    
script: ./gradlew assembleDebug