language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.1
    - android-19
    - android-21
    - android-23
    - android-24
    - android-26
    - android-28
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-21
    - extra-google-m2repository
    - extra-android-m2repository
    
script: ./gradlew build connectedCheck